fix: update ephemeral-test-env workflow

diff --git a/.github/workflows/ephemeral-test-env.yaml b/.github/workflows/ephemeral-test-env.yaml
--- a/.github/workflows/ephemeral-test-env.yaml
+++ b/.github/workflows/ephemeral-test-env.yaml
@@ -23,17 +23,17 @@ env:
   DOTNET_INSTALL_DIR: "./.dotnet"
 
 jobs:
-  set-matrix-and-namespace:
+  set-matrix-and-namespace-and-namespace:
     runs-on: ephemeral-env-runner
     outputs:
-      matrix: ${{ steps.set-matrix.outputs.matrix }}
+      matrix: ${{ steps.set-matrix-and-namespace.outputs.matrix }}
       namespace: ${{ steps.namespace.outputs.namespace }}
     steps:
       - name: Install jq
         run: sudo apt-get update && sudo apt-get install -y jq
 
       - name: Set matrix
-        id: set-matrix
+        id: set-matrix-and-namespace
         run: |
           # Set matrix based on service input
           service="${{ github.event.inputs.service }}"
@@ -76,10 +76,10 @@ jobs:
 
   publish:
     runs-on: ephemeral-env-runner
-    needs: set-matrix-and-namespace
+    needs: set-matrix-and-namespace-and-namespace
     strategy:
       matrix:
-        servicename: ${{ fromJson(needs.set-matrix-and-namespace.outputs.matrix) }}
+        servicename: ${{ fromJson(needs.set-matrix-and-namespace-and-namespace.outputs.matrix) }}
     steps:
       # Checkout source code
       - name: Checkout code
@@ -114,11 +114,11 @@ jobs:
           retention-days: 1
 
   build-and-push-image:
-    needs: set-matrix-and-namespace, publish
+    needs: [set-matrix-and-namespace-and-namespace, publish]
     runs-on: ephemeral-env-runner
     strategy:
       matrix:
-        servicename: ${{ fromJson(needs.set-matrix-and-namespace.outputs.matrix) }}
+        servicename: ${{ fromJson(needs.set-matrix-and-namespace-and-namespace.outputs.matrix) }}
     permissions:
       contents: read
     outputs:
@@ -198,7 +198,7 @@ jobs:
 
   update-ephemeral-test-env:
     runs-on: ephemeral-env-runner
-    needs: build-and-push-image
+    needs: [set-matrix-and-namespace-and-namespace, build-and-push-image]
     steps:
       # Checkout code
       - name: Checkout code
@@ -230,8 +230,8 @@ jobs:
         run: |
           # Check if namespace exists
           echo "Checking if we can list namespaces..."
-          kubectl get namespace ${{ needs.set-matrix.outputs.namespace }} > /dev/null || { echo "Error: Cannot list ${{ needs.set-matrix.outputs.namespace }}. Please ensure the the namespace exists"; exit 1; }
-          echo "Namespace ${{ needs.set-matrix.outputs.namespace }} exists"
+          kubectl get namespace ${{ needs.set-matrix-and-namespace.outputs.namespace }} > /dev/null || { echo "Error: Cannot list ${{ needs.set-matrix-and-namespace.outputs.namespace }}. Please ensure the the namespace exists"; exit 1; }
+          echo "Namespace ${{ needs.set-matrix-and-namespace.outputs.namespace }} exists"
 
       - name: Update ephemeral-test-env image
         run: |
@@ -239,40 +239,40 @@ jobs:
           if [[ "$service" == "All" ]]; then
             # Update authserver
             echo "Updating all services"
-            kubectl patch deployment ${{ needs.set-matrix.outputs.namespace }}-authserver -n ${{ needs.set-matrix.outputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
+            kubectl patch deployment ${{ github.event.inputs.project_name }}-authserver -n ${{ needs.set-matrix-and-namespace.outputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
             echo "Waiting for authserver to be updated..."
-            kubectl rollout status deployment ${{ needs.set-matrix.outputs.namespace }}-authserver -n ${{ needs.set-matrix.outputs.namespace }} --timeout=300s
+            kubectl rollout status deployment ${{ needs.set-matrix-and-namespace.outputs.namespace }}-authserver -n ${{ needs.set-matrix-and-namespace.outputs.namespace }} --timeout=300s
             echo "Authserver updated successfully"
 
             echo "Updating silo"
-            kubectl patch deployment ${{ needs.set-matrix.outputs.namespace }}-silo -n ${{ needs.set-matrix.outputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
+            kubectl patch deployment ${{ github.event.inputs.project_name }}-silo -n ${{ needs.set-matrix-and-namespace.outputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
             echo "Waiting for silo to be updated..."
-            kubectl rollout status deployment ${{ needs.set-matrix.outputs.namespace }}-silo -n ${{ needs.set-matrix.outputs.namespace }} --timeout=300s
+            kubectl rollout status deployment ${{ needs.set-matrix-and-namespace.outputs.namespace }}-silo -n ${{ needs.set-matrix-and-namespace.outputs.namespace }} --timeout=300s
             echo "Silo updated successfully"
 
             echo "Updating httpapi"
-            kubectl patch deployment ${{ needs.set-matrix.outputs.namespace }}-httpapi -n ${{ needs.set-matrix.outputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
+            kubectl patch deployment ${{ github.event.inputs.project_name }}-httpapi -n ${{ needs.set-matrix-and-namespace.outputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
             echo "Waiting for httpapi to be updated..."
-            kubectl rollout status deployment ${{ needs.set-matrix.outputs.namespace }}-httpapi -n ${{ needs.set-matrix.outputs.namespace }} --timeout=300s
+            kubectl rollout status deployment ${{ needs.set-matrix-and-namespace.outputs.namespace }}-httpapi -n ${{ needs.set-matrix-and-namespace.outputs.namespace }} --timeout=300s
             echo "Httpapi updated successfully"
           elif [[ "$service" == "Aevatar.DbMigrator" ]]; then
             echo "Updating dbmigrator job"
-            kubectl delete job ${{ needs.set-matrix.outputs.namespace }}-dbmigrator -n ${{ needs.set-matrix.outputs.namespace }} --ignore-not-found
-            kubectl create job ${{ needs.set-matrix.outputs.namespace }}-dbmigrator \
+            kubectl delete job ${{ github.event.inputs.project_name }}-dbmigrator -n ${{ needs.set-matrix-and-namespace.outputs.namespace }} --ignore-not-found
+            kubectl create job ${{ github.event.inputs.project_name }}-dbmigrator \
               --image=sha-${{ needs.build-and-push-image.outputs.short_sha }} \
-              -n ${{ needs.set-matrix.outputs.namespace }} \
+              -n ${{ needs.set-matrix-and-namespace.outputs.namespace }} \
               -- /bin/bash -c "dotnet Aevatar.DbMigrator.dll"
           elif [[ "$service" == "Aevatar.AuthServer" ]]; then
             echo "Updating authserver"
-            kubectl patch deployment ${{ needs.set-matrix.outputs.namespace }}-authserver -n ${{ needs.set-matrix.outputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
+            kubectl patch deployment ${{ github.event.inputs.project_name }}-authserver -n ${{ needs.set-matrix-and-namespace.outputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
             echo "Waiting for authserver to be updated..."
-            kubectl rollout status deployment ${{ needs.set-matrix.outputs.namespace }}-authserver -n ${{ needs.set-matrix.outputs.namespace }} --timeout=300s
+            kubectl rollout status deployment ${{ needs.set-matrix-and-namespace.outputs.namespace }}-authserver -n ${{ needs.set-matrix-and-namespace.outputs.namespace }} --timeout=300s
             echo "Authserver updated successfully"
           elif [[ "$service" == "Aevatar.HttpApi.Host" ]]; then
             echo "Updating httpapi"
-            kubectl patch deployment ${{ needs.set-matrix.outputs.namespace }}-httpapi -n ${{ needs.set-matrix.outputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
+            kubectl patch deployment ${{ github.event.inputs.project_name }}-httpapi -n ${{ needs.set-matrix-and-namespace.outputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
             echo "Waiting for httpapi to be updated..."
-            kubectl rollout status deployment ${{ needs.set-matrix.outputs.namespace }}-httpapi -n ${{ needs.set-matrix.outputs.namespace }} --timeout=300s
+            kubectl rollout status deployment ${{ needs.set-matrix-and-namespace.outputs.namespace }}-httpapi -n ${{ needs.set-matrix-and-namespace.outputs.namespace }} --timeout=300s
             echo "Httpapi updated successfully"
           else
             echo "Invalid service input"
