fix: update ephemeral-test-env workflow

diff --git a/.github/workflows/ephemeral-test-env.yaml b/.github/workflows/ephemeral-test-env.yaml
--- a/.github/workflows/ephemeral-test-env.yaml
+++ b/.github/workflows/ephemeral-test-env.yaml
@@ -6,10 +6,6 @@ on:
       project_name:
         description: "Project name"
         required: true
-      namespace:
-        description: "Namespace"
-        required: true
-        default: "${{ github.event.inputs.project_name }}-ephemeral-test-1"
       service:
         description: "Service name"
         required: true
@@ -31,6 +27,7 @@ jobs:
     runs-on: ephemeral-env-runner
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
+      namespace: ${{ steps.namespace.outputs.namespace }}
     steps:
       - name: Set matrix
         id: set-matrix
@@ -69,6 +66,15 @@ jobs:
             exit 1
           fi
           echo "matrix=$matrix" >> "$GITHUB_OUTPUT"
+
+      - name: Set Namespace
+        id: namespace
+        run: |
+          NAMESPACE="${{ github.event.inputs.namespace }}"
+          if [[ -z "$NAMESPACE" ]]; then
+            NAMESPACE="${{ github.event.inputs.project_name }}-ephemeral-test-1"
+          fi
+          echo "namespace=$NAMESPACE" >> "$GITHUB_OUTPUT"
 
   publish:
     runs-on: ephemeral-env-runner
@@ -225,8 +231,8 @@ jobs:
         run: |
           # Check if namespace exists
           echo "Checking if we can list namespaces..."
-          kubectl get namespace ${{ github.event.inputs.namespace }} > /dev/null || { echo "Error: Cannot list ${{ github.event.inputs.namespace }}. Please ensure the the namespace exists"; exit 1; }
-          echo "Namespace ${{ github.event.inputs.namespace }} exists"
+          kubectl get namespace ${{ needs.set-matrix.outputs.namespace }} > /dev/null || { echo "Error: Cannot list ${{ needs.set-matrix.outputs.namespace }}. Please ensure the the namespace exists"; exit 1; }
+          echo "Namespace ${{ needs.set-matrix.outputs.namespace }} exists"
 
       - name: Update ephemeral-test-env image
         run: |
@@ -234,44 +240,42 @@ jobs:
           if [[ "$service" == "All" ]]; then
             # Update authserver
             echo "Updating all services"
-            kubectl patch deployment ${{ github.event.inputs.namespace }}-authserver -n ${{ github.event.inputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
+            kubectl patch deployment ${{ needs.set-matrix.outputs.namespace }}-authserver -n ${{ needs.set-matrix.outputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
             echo "Waiting for authserver to be updated..."
-            kubectl rollout status deployment ${{ github.event.inputs.namespace }}-authserver -n ${{ github.event.inputs.namespace }} --timeout=300s
+            kubectl rollout status deployment ${{ needs.set-matrix.outputs.namespace }}-authserver -n ${{ needs.set-matrix.outputs.namespace }} --timeout=300s
             echo "Authserver updated successfully"
 
             echo "Updating silo"
-            kubectl patch deployment ${{ github.event.inputs.namespace }}-silo -n ${{ github.event.inputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
+            kubectl patch deployment ${{ needs.set-matrix.outputs.namespace }}-silo -n ${{ needs.set-matrix.outputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
             echo "Waiting for silo to be updated..."
-            kubectl rollout status deployment ${{ github.event.inputs.namespace }}-silo -n ${{ github.event.inputs.namespace }} --timeout=300s
+            kubectl rollout status deployment ${{ needs.set-matrix.outputs.namespace }}-silo -n ${{ needs.set-matrix.outputs.namespace }} --timeout=300s
             echo "Silo updated successfully"
 
             echo "Updating httpapi"
-            kubectl patch deployment ${{ github.event.inputs.namespace }}-httpapi -n ${{ github.event.inputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
+            kubectl patch deployment ${{ needs.set-matrix.outputs.namespace }}-httpapi -n ${{ needs.set-matrix.outputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
             echo "Waiting for httpapi to be updated..."
-            kubectl rollout status deployment ${{ github.event.inputs.namespace }}-httpapi -n ${{ github.event.inputs.namespace }} --timeout=300s
+            kubectl rollout status deployment ${{ needs.set-matrix.outputs.namespace }}-httpapi -n ${{ needs.set-matrix.outputs.namespace }} --timeout=300s
             echo "Httpapi updated successfully"
-
           elif [[ "$service" == "Aevatar.DbMigrator" ]]; then
             echo "Updating dbmigrator job"
-            kubectl delete job ${{ github.event.inputs.namespace }}-dbmigrator -n ${{ github.event.inputs.namespace }} --ignore-not-found
-            kubectl create job ${{ github.event.inputs.namespace }}-dbmigrator \
+            kubectl delete job ${{ needs.set-matrix.outputs.namespace }}-dbmigrator -n ${{ needs.set-matrix.outputs.namespace }} --ignore-not-found
+            kubectl create job ${{ needs.set-matrix.outputs.namespace }}-dbmigrator \
               --image=sha-${{ needs.build-and-push-image.outputs.short_sha }} \
-              -n ${{ github.event.inputs.namespace }} \
+              -n ${{ needs.set-matrix.outputs.namespace }} \
               -- /bin/bash -c "dotnet Aevatar.DbMigrator.dll"
-
           elif [[ "$service" == "Aevatar.AuthServer" ]]; then
             echo "Updating authserver"
-            kubectl patch deployment ${{ github.event.inputs.namespace }}-authserver -n ${{ github.event.inputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
+            kubectl patch deployment ${{ needs.set-matrix.outputs.namespace }}-authserver -n ${{ needs.set-matrix.outputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
             echo "Waiting for authserver to be updated..."
-            kubectl rollout status deployment ${{ github.event.inputs.namespace }}-authserver -n ${{ github.event.inputs.namespace }} --timeout=300s
+            kubectl rollout status deployment ${{ needs.set-matrix.outputs.namespace }}-authserver -n ${{ needs.set-matrix.outputs.namespace }} --timeout=300s
             echo "Authserver updated successfully"
-
           elif [[ "$service" == "Aevatar.HttpApi.Host" ]]; then
             echo "Updating httpapi"
-            kubectl patch deployment ${{ github.event.inputs.namespace }}-httpapi -n ${{ github.event.inputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
+            kubectl patch deployment ${{ needs.set-matrix.outputs.namespace }}-httpapi -n ${{ needs.set-matrix.outputs.namespace }} --type=json -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "sha-${{ needs.build-and-push-image.outputs.short_sha }}"}]'
             echo "Waiting for httpapi to be updated..."
-            kubectl rollout status deployment ${{ github.event.inputs.namespace }}-httpapi -n ${{ github.event.inputs.namespace }} --timeout=300s
+            kubectl rollout status deployment ${{ needs.set-matrix.outputs.namespace }}-httpapi -n ${{ needs.set-matrix.outputs.namespace }} --timeout=300s
             echo "Httpapi updated successfully"
-            
           else
             echo "Invalid service input"
+            exit 1
+          fi
